### ISSUE TITLE
request qt2ut migration tool

### ISSUE THREAD

**Issue by ylxb2016** [rumanzo/bt2qbt#1]
Hi, rumanzo,

Is there a similar tool to  migration from qBittorrent to uTorrent?

**Comment by rumanzo** [comment]
Hi! Technically, it is no problem (just time) make new app from bt2qbt, but I don't understand why anyone may wish this :-)
Seriously, old version of ut crashes, new versions worse from version to version, ut contain a lot of ad, commercialtechnical support not really work and community forum are dead, and it's closed source.

**Comment by ylxb2016** [comment]
Wow, it't great! 
I have searched a tool to migrate from qbittorrent to utorrent.I always use the utorrent 2.0.4 and 2.2 because of their extremely  powerful stability and utorrent save memory especially in old PC. In fact, utorrent users are more than other clients on the most trackers.
Thank you!

**Comment by rumanzo** [comment]
Stop stop stop. Don't thank me, may be, someday, I will get to do this, but in any case this requires a week of work in the evenings, for coding, tests, and so on, and now I don't have free time. And in general this is all a dubious idea, utorrent is bad software, like i write earlier.
If you don't want to wait, you can adapt my code or write the same thing on python, it will be much easier.

**Comment by ylxb2016** [comment]
Hah, :)
Thank you Anyway.

**Comment by Nuevo009** [comment]
Maybe it's a bit late, but I wrote a similar tool based on node.js and python. The code is poorly written and I don’t have time to do more tests. But maybe someone can try this https://github.com/Nuevo009/qb2ut.

**Comment by ylxb2016** [comment]
Thanks Nuevo009! It's never too late to have a great tool.
