### ISSUE TITLE
initial backslash missing from paths

### ISSUE THREAD

**Issue by bilditup1** [rumanzo/bt2qbt#14]
Not sure why but a few of the torrents imported have an invalid path of <drive-letter>**:**<rest-of-path>, when it needs to be: <drive-letter>**:\**<rest-of-path>. Otherwise the torrent errors out. Attempting to change the path via the qBittorrent UI doesn't actually change it. I don't actually know what is causing this. For what it's worth all of the torrents that have this is issue have the drive letter X: (but not all torrents with said drive letter have this issue). Using your qbtchangetracker, I was able to rename the paths to include that initial backslash. Unclear if you will be able to reproduce--can send my uTorrent resume file (from uT 2.2.1) if this is helpful.

**Comment by rumanzo** [comment]
Please send resume.dat, one of the problem torrent file and its fastresume file (not edited), this will help me a lot

**Comment by bilditup1** [comment]
OK, I can do that--I'm not sure what a fastresume file is though, or where it could be found

**Comment by rumanzo** [comment]
Hash of torrent you may see in Qbittorrent on general tab ("Torrent hash"), you can find it on %LOCALAPPDATA%\qBittorrent\BT_backup (just put it in windows explorer), you need find filehash.fastresume

**Comment by bilditup1** [comment]
OK--to be clear, do you want me to recreate the fastresume that existed before I fixed the path then, or does that not matter? This will require me, I guess, to set up a new installation of qbt (I guess on a different machine?) and importing uTorrent's resume file there.

**Comment by rumanzo** [comment]
Best option - copy qBittorrent.ini to another place, create temp directory and use keys -c to copied qBittorrent.ini and -d flag to temp directory
