### ISSUE TITLE
file priority mappings sometimes incorrect--downloaded files marked as 0%

### ISSUE THREAD

**Issue by bilditup1** [rumanzo/bt2qbt#15]
uTorrent has download priority levels per file of 0-15, with 0 = do not download and 15 = highest priority. But it looks like some torrents with files of low download priority--but nonetheless, not zero--are mapped to a download priority of 'do not download' in qBittorrent by bt2qbt. This results in the files being marked as not having been downloaded, even though they have been. Torrent must be paused, each file enabled by hitting their respective checkmarks, and then entire torrent rechecked in order for the files to be recognized. Unclear to me exactly when this happens, if there's a priority  threshold below which a torrent is marked as 'not downloaded' or what, --next time I come across one, can (gulp) reopen uT and take notes of  the download priorities for the torrent in question.

**Comment by rumanzo** [comment]
https://github.com/rumanzo/bt2qbt/blob/master/libtorrent/torrent.go#L132-L146
That code I write for priority collation. I think it's my be because in resume.dat for torrent priority which I could not take into account. Fix will be soon

**Comment by rumanzo** [comment]
I plan to post a new version after closing https://github.com/rumanzo/bt2qbt/issues/14

**Comment by bilditup1** [comment]
This is incredibly responsive. Thanks for the fixes as well as writing these tools in the first place!
