### ISSUE TITLE
Might wanna use value["caption"] for torrent names

### ISSUE THREAD

**Issue by j1warren** [rumanzo/bt2qbt#2]
I have many edited torrent names, so you might wanna use value["caption"] for torrent names or create an option for it.

Also, I've migrated from windows utorrent to linux qbt, so had to edit paths. Some people might find it useful.
Edit the end of fillsavepaths() function:

```
	//newstructure.QbtsavePath = newstructure.Save_path

	str := ""
	var replacer = strings.NewReplacer("f:", "F:", "g:", "G:", "\\", "/")
	var replacer2 = strings.NewReplacer(
	"F:/Games", "/home/username/games",
	"G:/mybackups", "/mnt/seagate/backups",
	"//", "/")


	str = replacer.Replace(newstructure.Save_path)
	newstructure.Save_path = replacer2.Replace(str)
	
	for i := range newstructure.Mapped_files {
		str = replacer.Replace(newstructure.Mapped_files[i])
		newstructure.Mapped_files[i] = replacer2.Replace(str)
	}
	
	newstructure.QbtsavePath = newstructure.Save_path
	fmt.Println("%v\n%v\n", newstructure.Save_path, newstructure.Mapped_files)
}
```

**Comment by rumanzo** [comment]
Hello! Thanks for the feedback. I did not think that anyone might need this kind of migration, I will think about how best to do it. But I am very busy now, it's work need time.
If you want, you may send a pull request

**Comment by rumanzo** [comment]
#4
