### ISSUE TITLE
Trouble going from windows BT to Ubuntu QT

### ISSUE THREAD

**Issue by Talz996** [rumanzo/bt2qbt#20]
Either my -t and -r are getting ignored, or I'm doing something wrong here - likely the latter.  My old BT instance was dumping the torrent files to a network share \\FREENAS\Files\Torrent files\ which I've remapped to new ubuntu QT as /home/talz/nfs/files/Torrent files/ and resume.dat has been copied to the network share mapped as /home/talz/nfs/files/resume.dat

Syntax:
./bt2qbt_v1.6_amd64_linux -r '\\FREENAS\Files\Torrent files\,/home/talz/nfs/files/Torrent files/' -r '\\FREENAS\Media\Videos\,/home/talz/nfs/videos/' -r '\\FREENAS\Media\Torrents\,/home/talz/nfs/torrents/' -t '/home/talz/nfs/files/Torrent files/' -s '/home/talz/' --sep='\'

Result:
###/### Can't find torrent file /home/talz/\\FREENAS\Files\Torrent files\xxx.torrent for \\FREENAS\Files\Torrent files\xxx.torrent

**Comment by rumanzo** [comment]
Hi. Found problem there https://github.com/rumanzo/bt2qbt/blob/master/bt2qbt.go#L166-L175 , did not expect that there might be a network share. I need time to fix it.

**Comment by rumanzo** [comment]
Try version 1.7 https://github.com/rumanzo/bt2qbt/releases
In your case you need define source (-s flag) with folder, that contain resume.dat, and -t flag with path to folder, that contain yours torrent files. And notice that bt2qbt don't do recursive search, paths must be accurate

**Comment by Talz996** [comment]
> 
> 1405/1407 Can't find torrent file /home/talz/nfs/files/\\FREENAS\Files\Torrent files\xxx.torrent for \\FREENAS\Files\Torrent files\xxx.torrent 
> 1406/1407 Can't find torrent file /home/talz/nfs/files/\\FREENAS\Files\Torrent files\xxx.torrent for \\FREENAS\Files\Torrent files\xxx.torrent 
> 1407/1407 Can't find torrent file /home/talz/nfs/files/\\FREENAS\Files\Torrent files\xxx.torrent for \\FREENAS\Files\Torrent files\xxx.torrent 
> 
> 2020/10/26 17:49:45 Ended
> 2020/10/26 17:49:45 Not all torrents was processed

Syntax:
./bt2qbt_v1.7_amd64_linux -r '\\FREENAS\Files\Torrent files\,/home/talz/nfs/files/Torrent files/' -r '\\FREENAS\Media\Videos\,/home/talz/nfs/videos/' -r '\\FREENAS\Media\Torrents\,/home/talz/nfs/torrents/' -t '/home/talz/nfs/files/Torrent files/' -s '/home/talz/nfs/files' --sep='\'

Is it detecting the OS to run based on the resume.dat or the file/OS I'm working in?  Perhaps I have a problem there?

Thanks for your help/script!

**Comment by Talz996** [comment]
ln '/home/talz/nfs/files/Torrent files/'
returns all my files, so I believe that part is correct.

**Comment by rumanzo** [comment]
try this (I don't now, in resume.dat one backslash or two):
`
./bt2qbt_v1.7_amd64_linux -r '\\FREENAS\Media\Videos\,/home/talz/nfs/videos/' -r '\\FREENAS\Media\Torrents\,/home/talz/nfs/torrents/' -t '/home/talz/nfs/files/Torrent files/' -s '/home/talz/nfs/files'
`
where  '/home/talz/nfs/files' is directory with resume.dat, '/home/talz/nfs/files/Torrent files/' directory with torrent files

> Thanks for your help/script!

Technically bt2qbt is not a script :-)

**Comment by rumanzo** [comment]
And I make mistake. Use version 1.8

**Comment by Talz996** [comment]
Slam dunk!  It's trudging it's way through rechecking several TiB of junk now.  The benefits of QBT+NFS over UT+SMB are already quite apparent.  Wish I'd have done this a long time ago.
