### ISSUE TITLE
v1.10 Release clarification 

### ISSUE THREAD

**Issue by AdKiller** [rumanzo/bt2qbt#26]
Sorry I don't understand what was fixed in v1.10 Release. Could you please provide an example for what was broken?

Should I re-do my utorrent to qbittorrent transfer that I just did using v1.9 ?

**Comment by rumanzo** [comment]
You can read there https://qbforums.shiki.hu/viewtopic.php?f=14&t=5889&start=165
Between 1.3 and 1.10 after transfer you can see incorrect remaining and size values for incompleted torrent. Nothing serious, if it's a problem for you - you can reimport from uTorrent, if not - don't worry about.
