### ISSUE TITLE
Could you please give a hint how the mac build works?

### ISSUE THREAD

**Issue by borost1** [rumanzo/bt2qbt#3]
**The released mac version is an unrecognizable binary by the OS.**

Could you give some hint how to use it?

**Comment by rumanzo** [comment]
Hi!
$ file bt2qbt_v1.1_amd64_macos                                                                                                    
bt2qbt_v1.1_amd64_macos: Mach-O 64-bit x86_64 executable

What version of operating system do you have? What kind of architecture, x86_64?
