### ISSUE TITLE
Some save paths are incorrect

### ISSUE THREAD

**Issue by freonpsandoz** [rumanzo/bt2qbt#32]
All torrents that were renamed on addition to uTorrent display a save path that includes the renamed folder, but uTorrent correctly shows these torrents as having the save folder selected by the user.

**To Reproduce**

Add two torrents to uTorrent. Use the same save path for both. Leave the name unchanged for one and change the name of the other. Exit uTorrent and run bt2qbt. When qbittorrent is run, it will show the save path for the renamed torrent as a full path to the folder with the new name, while the save folder for the other one is correct.

**Expected behavior**

The save path should be the same for both torrents.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser: Chrome 92.0.4515.107
 - bt2qbt version: v1.11_amd_64

**Additional context**

It isn't clear how uTorrent determines the save path. The sections of the uTorrent resume.dat file appear the same for both torrents. However, for the renamed torrent, uTorrent appears to create a .torrent file with the new name. Perhaps it compares that name to the internal name and that's how it recognizes that the save path wasn't changed by the user?

**Comment by rumanzo** [comment]
I know it's been a long time, sory for that, I was very busy. But now I refactoring bt2qbt and cover it with tests.
I will append this test case, if it doesn't exists yet

**Comment by rumanzo** [comment]
I think this case is what you talk about https://github.com/rumanzo/bt2qbt/blob/refactor/internal/transfer/transfer_test.go#L94-L121

**Comment by rumanzo** [comment]
Should be fixed with https://github.com/rumanzo/bt2qbt/pull/35
