### ISSUE TITLE
Can't decode uTorrent\Bittorrent resume file

### ISSUE THREAD

**Issue by marcinwasilewski** [rumanzo/bt2qbt#34]
When I run the macOS build it tells me that it cannot decode the resume.file

```
~> ./bt2qbt_v1.11_amd64_macos -s ~/Library/Application\ Support/uTorrent\ Web                                                                                                                    
2021/11/19 18:59:03 Can't decode uTorrent\Bittorrent resume file
```

 - OS: BigSur 11.4
 - μTorrent Web Version 1.2.3.3777 (8475)
 - bt2qbt v1.11

**Comment by yquenechdu** [comment]
same problem with Mac OS 

I have some issue on Mac OS version 11.5.1 Big Sur

I use this command : bt2qbt_v1.11_amd64_macos -s /Users/me/Library/Application\ Support/uTorrent\ Web

Where there is the file : resume.dat

I obtain this error message : Can't decode uTorrent\Bittorrent resume file

Utorrent version : μTorrent Web Version 1.2.7.4187 (9051)
qBittorent v4,3.9 (64bits)

**Comment by rumanzo** [comment]
> ~/Library/Application\ Support/uTorrent\ Web

why you use different slashes and have spaces in the path?

**Comment by yquenechdu** [comment]
Because Apple you use space for the directory "Application Support" and utorrent app use the dir : "uTorrent Web". Apple use \ to indicate a space dir in path. 

I use the command directly in utorrent folder : ./bt2qbt_v1.11_amd64_macos -s resume.dat  
I obtain the same error message : Can't decode uTorrent\Bittorrent resume file

**Comment by rumanzo** [comment]
> ./bt2qbt_v1.11_amd64_macos -s resume.dat

It shouldn't work



> Because Apple you use space for the directory "Application Support" and utorrent app use the dir : "uTorrent Web". Apple use \ to indicate a space dir in path.

Try enclosing the path in quotes without backslashes

**Comment by yquenechdu** [comment]
> 

HI,

"\"  is a classic command linux or Unix for directory with space...

 I tested with the path in quotes : 

./bt2qbt_v1.11_amd64_macos -s "/Users/yannick/Library/Application Support/uTorrent Web/"
Can't decode uTorrent\Bittorrent resume file

Same result.

**Comment by rumanzo** [comment]
Can you show me what exists in directory /Users/yannick/Library/Application Support/uTorrent Web/ ?
Also I never touch utorrent web version, it can be different

**Comment by va-r-un** [comment]
@yquenechdu did it work for utorrent web. I am on windows and getting same error.
