### ISSUE TITLE
trackers URL/announce are not imported

### ISSUE THREAD

**Issue by AirNest** [rumanzo/bt2qbt#36]
first thing: great tool! thanks for it! :)

**Describe the bug**
maybe i forgot something but when I use the tool to import torrents from uTorrent (or BitTorrent), the trackers URL are missing

**To Reproduce**
1. for uTorrent, just launching bt2qbt_v1.14_amd64.exe with double clic
2. wait for import
3. XXXX/YYYY Sucessfully imported ZZZZ.torrent
4. open QBittorrent
5. torrents are imported but the column "tracker" is void, same for the "tracker" tab of the torrents

**Expected behavior**
i think the trackers should be imported with the torrents
in case of cross-seeding or if we are on multiple trackers, it will be a nightmare to match each torrent with its tracker
i think it's the same problem with multi-tracking torrents

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 x64 bits
 
**Screenshots**

source of the torrent on BitTorrent: 
![1 3](https://user-images.githubusercontent.com/43614032/161525048-178490d6-5d54-4310-86c0-a276b68ca1db.png)

source with tracker tab:
![1 4](https://user-images.githubusercontent.com/43614032/161525675-95cdae15-70bb-4f91-8e30-436b61ae51a0.png)

after import
![1 1](https://user-images.githubusercontent.com/43614032/161525192-ffe74cad-67f1-475e-b21d-e4506896161d.png)

after import with tracker tab (and menu on the left)
![1 2](https://user-images.githubusercontent.com/43614032/161525291-6a0571eb-8ef3-439f-8c00-349e920a03b7.png)

if necessary i made screens for the 2 similar torrents (cross-seeding)

**Comment by rumanzo** [comment]
Hello! Very intresing case. What hashes have bittorrents's torrens with diffirent trackers ?
Do you have problem only with these torrents?

**Comment by rumanzo** [comment]
Found a bug. Making hotfix

**Comment by rumanzo** [comment]
I make hotfix https://github.com/rumanzo/bt2qbt/releases/tag/v1.15 , try this version and tell me result

Thank you for report

**Comment by AirNest** [comment]
fixed! thanks for your fast answer!
![4](https://user-images.githubusercontent.com/43614032/161575743-10dfdfdc-50c2-4b37-adf4-dd00abae8d2c.png)
