### ISSUE TITLE
Extra backslash in the path

### ISSUE THREAD

**Issue by AirNest** [rumanzo/bt2qbt#40]
**Describe the bug**
because of an extra backslash added to the (root) path of the files, sometimes (not every time), we get an I/O error when launching Qbittorrent and the files are not found then shared

most of the time (for 235 on 237 torrents in my case) it affects torrents with only 1 file in it, when it's a root path and has the name of the file inside
torrents with more than 1 file in it doesn't seem to be affected (just 2 on 237 torrents in my case; maybe i used the "create a sub-folder" at the time for those 2 torrents and that's the reason?)

if the path mention a folder there isn't any problem with the extra backslash

**Expected behavior**
when the path is a root path, bt2qbt should check the number of backslash at the end of the path (before adding one or if there's already an extra one)
if it's the reason of the error?

**Screenshots**
the error message (in my language, "erreur E/S" means "I/O error"
![0 1](https://user-images.githubusercontent.com/43614032/164949010-1113cb9d-a268-41ab-abd5-31a4e5b615db.png)

the normal behavior with multiple files in the torrent:
![1 1](https://user-images.githubusercontent.com/43614032/164949033-2f217f9a-fb22-4d76-895b-53dc1eaa9ced.png)
![1 2](https://user-images.githubusercontent.com/43614032/164949041-263d05fb-6284-46e5-8b74-070dbf9bc5cc.png)
![1 3](https://user-images.githubusercontent.com/43614032/164949043-afcf443c-b249-4503-bfd5-07383c8aba36.png)
![1 4](https://user-images.githubusercontent.com/43614032/164949049-b1f86104-e920-43ac-a1ee-5377da33a528.png)

the wrong behavior with only 1 file in the torrent:
![2 1](https://user-images.githubusercontent.com/43614032/164949075-fa9ac12f-8c68-456d-a9d2-aebce793e25b.png)
![2 2](https://user-images.githubusercontent.com/43614032/164949078-8de84dbe-5f1c-4e99-ba48-1be507aa74fa.png)
![2 3](https://user-images.githubusercontent.com/43614032/164949079-560c6423-b03f-49ae-9d55-8bf2436cbbe0.png)
![2 4](https://user-images.githubusercontent.com/43614032/164949080-91714deb-6c24-43af-98db-3ed882842cc9.png)

no problem with "no root path"
![3 1](https://user-images.githubusercontent.com/43614032/164949185-9ab65370-2760-48a0-834c-47b4615170c3.png)
![3 2](https://user-images.githubusercontent.com/43614032/164949188-a61680b8-6c6a-4469-bd74-701b7c0f36a8.png)
![4 1](https://user-images.githubusercontent.com/43614032/164949191-8667a0ed-61e2-4de5-97ae-bedabcf77055.png)
![4 2](https://user-images.githubusercontent.com/43614032/164949193-ab509765-6fe1-49bb-953c-eed6bc7e884a.png)

and what surprises me the most: for the majority of the torrents, there's no error despite the extra backslash O_O
![5 1](https://user-images.githubusercontent.com/43614032/164949973-f194f0a7-777b-42d7-8fc4-e0808a337e6c.png)
![5 2](https://user-images.githubusercontent.com/43614032/164949974-48fe3a52-01b7-42ab-ba99-f3426be612a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 x64 bits
 - versions of bt2qbt tested: bt2qbt_v1.14_amd64, bt2qbt_v1.15_amd64, bt2qbt_v1.17_amd64

thanks again for your great tool!

**Comment by AirNest** [comment]
correct!

**Comment by rumanzo** [comment]
Fixed in new release https://github.com/rumanzo/bt2qbt/releases/tag/v1.18
please check it
