### ISSUE TITLE
Subfolders/Subdirectories aren't created correctly

### ISSUE THREAD

**Issue by mjrawesome** [rumanzo/bt2qbt#42]
After transferring my torrents from BittorrentPro 7.10.5 to qBittorrent v4.5.2, I noticed that I cannot change category save paths as per usual, because all torrents are downloaded into one directory instead of their respective subfolders/subdirectories. 

Upon some investigation I noticed that subfolders are completely missing from the Content tab for all torrents and instead the subforder name has been appended to the Save Path for each torrent. The problem with this approach is that, like I mentioned, changing paths for any one torrent or for a group of torrents transferred from Bittorrent to qBittorrent is completely broken. The only way to change the save path for a torrent transferred with bt2qbt seems to be manually creating a new folder for every single torrent and pointing the torrent to that new folder.

Is there a workaround for this? Is it possible to change this behavior or is it a limitation of the program?

Thanks.

**Comment by rumanzo** [comment]
I don't completely understand the problem. Seems we need a fix, but I need more information.
How I can repeat this? I more interesting about type of torrent (single, multifile), and bittorrent enabled features and torrent params

**Comment by mjrawesome** [comment]
I appreciate your reply, @rumanzo.

To better illustrate what I mean I grabbed a few random torrents from the internet. I hope that this won't be problematic.

In Picture 1, you can see the torrent for Johnny Hamlet added to BittorrentPro. Since I selected the "Create subfolder" option when adding the torrent, all the files for that torrent will be downloaded into a subfolder called "Johnny Hamlet (1968) [ITA]". Notice the save path for this torrent is "G:\DOWNLOADS\MOVIES".

When I transfer this torrent with bt2qbt to qBittorrent, I get what you see in Picture 2. There is no subfolder shown in the "Contents" tab (see Point A) and the path is now "G:\DOWNLOADS\MOVIES\Johnny Hamlet (1968) [ITA]" instead of "G:\DOWNLOADS\MOVIES" (see Point B).

The problem with this approach is that it's now impossible to move that torrent to a different save path / category AND make the files (there are multiple files for that torrent) download into into a subfolder called "Johnny Hamlet (1968) [ITA]". When I move this torrent into, say, a category called "WATCHED MOVIES" which has the default save path of  "G:\DOWNLOADS\WATCHED MOVIES", all the files will be moved into the root directory and no subfolder will be created.

Instead, if you could make it so that after transfer, the torrent looks like in Picture 3, then it would be possible to move the torrent / download around and keep the folder structure. Notice the subfolder structure / option at Point C and the save path at Point D.

I also wanted to point out that making this, the solution in Picture 3, the default behaviour would be much less problematic, because moving files out of subfolders into the root directory can be accomplished with a simple script / commandline code. Whereas the opposite is not ture, because the information about the name of the subfolder is missing.

![Picture 1](https://user-images.githubusercontent.com/63406103/231867519-505e35df-fbfe-4878-8b2f-aafef4d6dea1.jpg)
![Picture 2](https://user-images.githubusercontent.com/63406103/231867553-a40e7d82-2090-4242-a534-3fc74308e93b.jpg)
![Picture 3](https://user-images.githubusercontent.com/63406103/231867572-f56c28ed-f7cd-4c83-a0e9-7e003906db31.jpg)

**Comment by mjrawesome** [comment]
I also noticed that selecting the option to **keep incomplete torrents separately** for the torrents imported with bt2qbt completely breaks those torrents, similarly to changing a category. That is, all files are dumped into a single root directory and if there is conflict in names, all torrents/downloads will end up corrupted.

**Comment by rumanzo** [comment]
It's looks that utorrent\bittorrent don't define any folder scheme in resume.dat. I will try workaround this

**Comment by rumanzo** [comment]
> To better illustrate what I mean I grabbed a few random torrents from the internet. I hope that this won't be problematic.

This case very strange, due exactly this case covered with tests https://github.com/rumanzo/bt2qbt/blob/master/internal/transfer/transfer_test.go#L295-L323

Can you send me bittorrent resume file and torrent file?

**Comment by rumanzo** [comment]
stuck since April
