### ISSUE TITLE
Files with Accented Characters are missing

### ISSUE THREAD

**Issue by m2840** [rumanzo/bt2qbt#49]
**Describe the bug**
Files with Accented Characters (portuguese) are declared missing. These characters are dropped or replaced by others.
For example: 01 Canção de Engate.mp3
Renaming the files in qBittorrent solved the problem, but requires doing it manually.

**To Reproduce**
Use bt2qbt_v1.21_amd64.exe to export uTorrent to qBittorrent

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser Firefox
 - Version 123.0.1

**Comment by rumanzo** [comment]
Thank you for the report. I'll check it

**Comment by rumanzo** [comment]
![image](https://github.com/rumanzo/bt2qbt/assets/15186512/e83b51cc-e1ee-4326-8fdd-12831c07d35c)
I can't reproduce this. Can you send torrent file to my email?

**Comment by m2840** [comment]
I checked the torrent I send to you with torrent-file-editor-0.3.18-x64.exe
I can see the .torrent name correctly by changing the coding from UTF-8 to ISO-8859-1. But the file names contain strange characters. For example: 01 Can��o de Engate.mp3 instead of 01 Canção de Engate.mp3
Maybe it's not worth to spend your time on it. These are old torrents. God knows what happened to them during their lifetime :-)

**Comment by m2840** [comment]
Just a final comment. Using torrent-file-editor-0.3.18-x64.exe in Tree view, the strings of the filenames also show correct characters if the coding is ISO-8859-1.

**Comment by rumanzo** [comment]
> I checked the torrent I send to you with torrent-file-editor-0.3.18-x64.exe I can see the .torrent name correctly by changing the coding from UTF-8 to ISO-8859-1. But the file names contain strange characters. For example: 01 Can��o de Engate.mp3 instead of 01 Canção de Engate.mp3 Maybe it's not worth to spend your time on it. These are old torrents. God knows what happened to them during their lifetime :-)

I usually use bencode editor. May be there some problem with character encoding, I used utf-8 in my test.
I haven't got you email yet

**Comment by rumanzo** [comment]
I made investigation. In both cases from is how decoded manually added torrent with all files renamed manually. I had to rename them cause they have different name in windows folder and libtorrent just change accented symbols to _. 
So actually if you append new torrent in qBittorrent, the name of file will be "01 Can_ de Engate.mp3"

there From is how I see files in windows folder after utorrent, and To is how bt2qbt transfer it
```
(diff.Changelog) (len=1 cap=1) {
 (diff.Change) {
  Type: (string) (len=6) "update",
  Path: ([]string) {
  },
  From: (string) (len=25) "01 Canзгo de Engate.mp3",
  To: (string) (len=23) "01 Can\xe7\xe3o de Engate.mp3",
  parent: (interface {}) <nil>
 }
}
```
As you can see, there latin1 (ISO-8859-1) symbols inside from torrent file, byte to byte. Actual file names don't have these symbols.



I tried to transform bytes to runes, and got actual file names in utf-8
```
(diff.Changelog) (len=1 cap=1) {
 (diff.Change) {
  Type: (string) (len=6) "update",
  Path: ([]string) {
  },
  From: (string) (len=25) "01 Canзгo de Engate.mp3",
  To: (string) (len=25) "01 Canção de Engate.mp3",
  parent: (interface {}) <nil>
 }
}
```
But on this step I've got 2 problems:
1.) this is still different from file names in folder
2.) I totally broke emojii support
And I can't guess only on input which codepage is it. 

I think I can't fix this totally

**Comment by rumanzo** [comment]
And by the way, I see saved files with names like `07 ...O Corpo Й Que Paga.mp3`, which make me think that way how utorrent save files (their names) on windows depends on system language (Russian, in my case), because I see Й.
How this files named in your system?

**Comment by m2840** [comment]
In my system the file is named 07 ...O Corpo É Que Paga.mp3
My Windows 10 is English (UK), but the "Regional format" is set to Portuguese and the "Current language for non-Unicode programs" is set to English (UK). Maybe all this definitions are the cause of the situation.
