### ISSUE TITLE
bt2qbt/releases - no 32bit version

### ISSUE THREAD

**Issue by emc2peer** [rumanzo/bt2qbt#6]
Hi rumanzo,

there is a wrong link to 32bit version of bt2qbt.
bt2qbt_v1.2_i386.exe is the same as bt2qbt_v1.2_amd64.exe (both are 64bit).
https://github.com/rumanzo/bt2qbt/releases

**Comment by rumanzo** [comment]
Oh! I'm sorry. Fix soon

**Comment by rumanzo** [comment]
I build binaries with new golang and create build script.
